'\" t
.\"     Title: git-lfs-logs
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GIT\-LFS\-LOGS" "1" "" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
git-lfs-logs \- Show errors from the git\-lfs command
.SH "SYNOPSIS"
.sp
.nf
.fam C
\fBgit lfs logs\fP
\fBgit lfs logs\fP \fI<file>\fP
\fBgit lfs logs clear\fP
\fBgit lfs logs boomtown\fP
.fam
.fi
.SH "DESCRIPTION"
.sp
Display errors from the git\-lfs command. Any time it crashes, the
details are saved to ".git/lfs/logs".
.SH "COMMANDS"
.sp
\f(CRclear\fP
.RS 4
Clears all of the existing logged errors.
.RE
.sp
\f(CRboomtown\fP
.RS 4
Triggers a dummy exception.
.RE
.SH "OPTIONS"
.sp
Without any options, \f(CRgit lfs logs\fP simply shows the list of error logs.
.sp
\f(CR<file>\fP
.RS 4
Shows the specified error log. Use "last" to show the most recent error.
.RE
.SH "SEE ALSO"
.sp
Part of the git\-lfs(1) suite.